name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6,3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pytest --cov=.
        coveralls
